/**
 * Cloudflare Worker: R2 Cloud Editor (Multi-Upload Fixed)
 * * 🎨 UI: Sanyue ImgHub 风格 + 玻璃拟态
 * * 🛠️ 新增: 大文件分片上传 (突破 100MB 限制)
 * * 🛠️ 新增: 右上角上传进度悬浮窗 + 🚀 速率/ETA显示
 * * 🛡️ 修复: 10MB 以上文件禁止预览，防止浏览器崩溃
 * * ⚡ 优化: 支持多文件并发上传 (修复只能传一个的问题)
 * * 🛠️ 优化: 改名自动同步、侧边栏拖拽、下载无需鉴权
 * * 🛠️ R2 存储桶绑定 变量名称: MY_BUCKET
 * * 🔐 鉴权用户名密码 变量名称: AUTH_USER / AUTH_SECRET
 */

// --- 1. 前端部分 (HTML + CSS + UI Logic) ---
const htmlParts = [
  '<!DOCTYPE html>',
  '<html lang="zh-CN">',
  '<head>',
  '  <meta charset="UTF-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">',
  '  <title>R2 Cloud Drive</title>',
  '  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>☁️</text></svg>">',
  '  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">',
  '  <style>',
  '    :root {',
  '      --bg-glass: rgba(30, 30, 30, 0.75);',
  '      --bg-glass-lighter: rgba(255, 255, 255, 0.05);',
  '      --bg-glass-sidebar: rgba(20, 20, 20, 0.85);',
  '      --border-glass: rgba(255, 255, 255, 0.1);',
  '      --text-primary: #e0e0e0;',
  '      --text-secondary: #a0a0a0;',
  '      --accent-gradient: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
  '      --danger-gradient: linear-gradient(135deg, #ff6b6b 0%, #c0392b 100%);',
  '      --accent-color: #667eea;',
  '      --danger-color: #ff6b6b;',
  '      --folder-color: #fbd38d;',
  '    }',
  '    ',
  '    body {',
  '      margin: 0;',
  '      font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
  '      background: url("https://bing.img.run/rand_1366x768.php") no-repeat center center fixed;',
  '      background-size: cover;',
  '      height: 100vh;',
  '      overflow: hidden;',
  '      display: flex;',
  '      justify-content: center;',
  '      align-items: center;',
  '      color: var(--text-primary);',
  '      transition: background-image 0.5s ease-in-out;',
  '    }',
  '',
  '    #app-container {',
  '      width: 96%;',
  '      height: 95vh;',
  '      max-width: none;',
  '      background: var(--bg-glass);',
  '      backdrop-filter: blur(20px);',
  '      -webkit-backdrop-filter: blur(20px);',
  '      border-radius: 16px;',
  '      border: 1px solid var(--border-glass);',
  '      box-shadow: 0 16px 40px rgba(0, 0, 0, 0.4);',
  '      display: flex;',
  '      overflow: hidden;',
  '      transition: transform 0.3s ease;',
  '      position: relative;',
  '    }',
  '',
  '    /* --- 侧边栏 --- */',
  '    #sidebar {',
  '      width: 360px;',
  '      min-width: 240px;',
  '      max-width: 600px;',
  '      background: var(--bg-glass-sidebar);',
  '      border-right: 1px solid var(--border-glass);',
  '      display: flex;',
  '      flex-direction: column;',
  '      flex-shrink: 0;',
  '      position: relative;',
  '      transition: background 0.3s;',
  '      z-index: 100;',
  '    }',
  '    ',
  '    .resizer {',
  '      width: 5px;',
  '      cursor: col-resize;',
  '      position: absolute;',
  '      top: 0; bottom: 0; right: 0;',
  '      z-index: 101;',
  '      transition: background 0.2s;',
  '    }',
  '    .resizer:hover, .resizer.resizing { background: var(--accent-color); }',
  '    ',
  '    #sidebar.drag-active {',
  '        background: rgba(102, 126, 234, 0.15);',
  '        box-shadow: inset 0 0 20px rgba(102, 126, 234, 0.3);',
  '        border-right: 2px dashed var(--accent-color);',
  '    }',
  '    #sidebar.drag-active::after {',
  '        content: "⬇️ 松手以上传文件到当前目录";',
  '        position: absolute;',
  '        top: 50%; left: 50%; transform: translate(-50%, -50%);',
  '        color: #fff; font-weight: bold; font-size: 16px;',
  '        pointer-events: none; text-align: center;',
  '        background: rgba(0,0,0,0.6); padding: 10px 20px; border-radius: 8px; z-index: 50;',
  '    }',
  '',
  '    .sidebar-header { padding: 20px; border-bottom: 1px solid var(--border-glass); }',
  '    #mobile-menu-btn, #mobile-back-btn { display: none; }',
  '',
  '    .logo-area { font-size: 18px; font-weight: 600; margin-bottom: 15px; display: flex; align-items: center; gap: 10px; color: #fff; letter-spacing: 0.5px; }',
  '',
  '    .header-actions { display: flex; gap: 4px; width: 100%; box-sizing: border-box; flex-wrap: wrap; }',
  '    .glass-btn {',
  '      background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.1); color: var(--text-primary);',
  '      padding: 6px 2px; border-radius: 6px; font-size: 12px; cursor: pointer; transition: all 0.3s;',
  '      display: flex; align-items: center; justify-content: center; gap: 2px; flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
  '      min-width: 60px;',
  '    }',
  '    .glass-btn:hover { background: rgba(255,255,255,0.2); transform: translateY(-1px); }',
  '    .btn-icon { flex: 0 0 32px; padding: 0; }',
  '',
  '    .path-bar { margin-top: 15px; font-family: monospace; font-size: 12px; color: var(--text-secondary); background: rgba(0,0,0,0.2); padding: 8px; border-radius: 6px; white-space: nowrap; overflow-x: auto; }',
  '    .path-bar::-webkit-scrollbar { height: 2px; } .path-bar::-webkit-scrollbar-thumb { background: var(--accent-color); }',
  '    #file-list { flex: 1; overflow-y: auto; padding: 10px; }',
  '    #file-list::-webkit-scrollbar { width: 4px; } #file-list::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); border-radius: 2px; }',
  '',
  '    .file-item { padding: 5px 8px; margin-bottom: 2px; border-radius: 6px; cursor: pointer; display: flex; justify-content: space-between; align-items: center; font-size: 13px; transition: all 0.2s; border: 1px solid transparent; }',
  '    .file-item:hover { background: var(--bg-glass-lighter); border-color: rgba(255,255,255,0.05); }',
  '    .file-item.active { background: rgba(102, 126, 234, 0.15); border-color: rgba(102, 126, 234, 0.3); color: #fff; }',
  '    .file-item.drag-target-hover { background: rgba(102, 126, 234, 0.3) !important; border: 1px dashed var(--accent-color) !important; box-shadow: 0 0 10px rgba(102, 126, 234, 0.2); }',
  '',
  '    .file-name-container { display: flex; align-items: center; gap: 8px; flex: 1; overflow: hidden; min-width: 0; }',
  '    .file-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '    .folder-icon { color: var(--folder-color); font-size: 16px; } .file-icon { opacity: 0.7; font-size: 16px; }',
  '    .actions { opacity: 0; transition: opacity 0.2s; display: flex; gap: 0px; } .file-item:hover .actions { opacity: 1; }',
  '    .icon-btn { background: transparent; border: none; color: var(--text-secondary); cursor: pointer; padding: 2px 4px; border-radius: 4px; transition: color 0.2s; font-size: 12px; }',
  '    .icon-btn:hover { color: #fff; background: rgba(255,255,255,0.1); } .del-btn:hover { color: var(--danger-color); }',
  '    .move-btn:hover { color: var(--accent-color); } .rename-btn:hover { color: #4faaff; }',
  '',
  '    /* --- 上下文菜单 --- */',
  '    .context-menu {',
  '       display: none; position: absolute; z-index: 2000;',
  '       background: rgba(40, 40, 40, 0.95);',
  '       border: 1px solid var(--border-glass);',
  '       border-radius: 8px; padding: 6px 0;',
  '       width: 160px; max-height: 80vh; overflow-y: auto;',
  '       box-shadow: 0 10px 30px rgba(0,0,0,0.5);',
  '       backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);',
  '    }',
  '    .context-menu::-webkit-scrollbar { width: 4px; }',
  '    .context-menu::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); border-radius: 2px; }',
  '    .menu-item { padding: 8px 16px; cursor: pointer; color: #eee; font-size: 13px; display: flex; align-items: center; gap: 10px; transition: background 0.2s; }',
  '    .menu-item:hover { background: var(--accent-color); color: #fff; }',
  '    .menu-item.disabled { opacity: 0.5; cursor: not-allowed; }',
  '    .menu-separator { height: 1px; background: rgba(255,255,255,0.1); margin: 4px 0; }',
  '',
  '    /* --- 主编辑区 --- */',
  '    #main { flex: 1; display: flex; flex-direction: column; background: transparent; overflow: hidden; }',
  '    .toolbar { padding: 15px 20px; border-bottom: 1px solid var(--border-glass); display: flex; gap: 15px; align-items: center; }',
  '    .toolbar-input { background: rgba(0,0,0,0.2); border: 1px solid var(--border-glass); color: #fff; padding: 8px 12px; border-radius: 8px; width: 300px; outline: none; font-size: 14px; transition: border-color 0.3s; }',
  '    .toolbar-input:focus { border-color: var(--accent-color); }',
  '    button.primary { background: var(--accent-gradient); color: white; border: none; padding: 8px 20px; border-radius: 50px; font-weight: 500; cursor: pointer; font-size: 13px; box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3); transition: all 0.3s; }',
  '    button.primary:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4); }',
  '    button.primary.danger-btn { background: var(--danger-gradient); box-shadow: 0 4px 15px rgba(255, 107, 107, 0.3); }',
  '    button.primary.danger-btn:hover { box-shadow: 0 6px 20px rgba(255, 107, 107, 0.4); }',
  '    #editor { flex: 1; background: transparent; color: #d4d4d4; border: none; padding: 25px; font-family: "Consolas", "Monaco", monospace; font-size: 14px; resize: none; outline: none; line-height: 1.6; }',
  '    #editor::placeholder { color: rgba(255,255,255,0.2); }',
  '    #editor:disabled { opacity: 0.6; cursor: not-allowed; color: #ff6b6b; font-weight: bold; }',
  '    #status { font-size: 12px; color: var(--text-secondary); opacity: 0.8; }',
  '    .rename-input { background: rgba(0,0,0,0.3); border: 1px solid var(--accent-color); color: white; border-radius: 4px; padding: 2px 5px; width: 90%; }',
  '',
  '    /* --- 上传进度悬浮窗 (右上角) --- */',
  '    #upload-progress-container {',
  '        position: fixed; top: 20px; right: 20px; width: 320px; z-index: 3000;',
  '        display: flex; flex-direction: column; gap: 10px;',
  '    }',
  '    .progress-card {',
  '        background: rgba(20, 20, 20, 0.9); border: 1px solid var(--border-glass);',
  '        backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);',
  '        border-radius: 8px; padding: 12px; color: #fff; box-shadow: 0 4px 15px rgba(0,0,0,0.5);',
  '        animation: slideIn 0.3s ease-out;',
  '    }',
  '    @keyframes slideIn { from { transform: translateX(100%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }',
  '    .progress-header { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 5px; }',
  '    .progress-filename { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 180px; }',
  '    .progress-bar-bg { height: 4px; background: rgba(255,255,255,0.1); border-radius: 2px; overflow: hidden; }',
  '    .progress-bar-fill { height: 100%; background: var(--accent-gradient); width: 0%; transition: width 0.2s; }',
  '    .progress-details { display: flex; justify-content: space-between; font-size: 10px; color: #aaa; margin-top: 4px; }',
  '',
  '    /* --- 模态框通用 --- */',
  '    .modal-overlay { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.6); backdrop-filter: blur(8px); z-index: 1000; justify-content: center; align-items: center; }',
  '    .modal-box { background: rgba(40, 40, 40, 0.95); border: 1px solid var(--border-glass); width: 450px; max-width: 90%; border-radius: 16px; box-shadow: 0 25px 50px rgba(0,0,0,0.5); overflow: hidden; animation: fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1); }',
  '    @keyframes fadeIn { from { opacity: 0; transform: scale(0.92); } to { opacity: 1; transform: scale(1); } }',
  '    .modal-header { padding: 20px; border-bottom: 1px solid var(--border-glass); display: flex; justify-content: space-between; align-items: center; font-weight: 600; color: #fff; font-size: 16px; }',
  '    .modal-body { padding: 25px 20px; font-size: 14px; color: #ccc; line-height: 1.6; }',
  '    .modal-footer { padding: 15px 20px; border-top: 1px solid var(--border-glass); display: flex; justify-content: flex-end; gap: 10px; background: rgba(0,0,0,0.2); }',
  '    .modal-close { cursor: pointer; opacity: 0.6; transition: 0.2s; font-size: 18px; } .modal-close:hover { opacity: 1; }',
  '    .info-row { display: flex; margin-bottom: 10px; border-bottom: 1px dashed rgba(255,255,255,0.1); padding-bottom: 8px; }',
  '    .info-label { width: 100px; color: var(--text-secondary); font-size: 13px; }',
  '    .info-value { color: #fff; font-family: monospace; word-break: break-all; font-size: 13px; }',
  '',
  '    .full-width-input { width: 100%; padding: 12px; box-sizing: border-box; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(0,0,0,0.3); color: #fff; outline: none; transition: border-color 0.3s; font-size: 14px; margin-bottom: 10px; }',
  '    .full-width-input:focus { border-color: var(--accent-color); }',
  '    .folder-select { width: 100%; padding: 10px; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(30,30,30,0.8); color: #eee; outline: none; margin-bottom: 15px; }',
  '',
  '    .login-box { width: 380px; text-align: center; }',
  '    .login-title { font-size: 20px; margin-bottom: 20px; display: block; font-weight: bold; background: var(--accent-gradient); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }',
  '    .login-input-group { margin-bottom: 15px; text-align: left; }',
  '    .login-input { width: 100%; padding: 12px; box-sizing: border-box; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(0,0,0,0.3); color: #fff; outline: none; transition: border-color 0.3s; font-size: 14px; }',
  '    .login-input:focus { border-color: var(--accent-color); }',
  '    .login-btn { width: 100%; padding: 12px; font-size: 16px; margin-top: 10px; }',
  '',
  '    /* --- 移动端 --- */',
  '    @media (max-width: 768px) {',
  '      #app-container { width: 94%; height: 92vh; border-radius: 16px; border: 1px solid var(--border-glass); flex-direction: column; overflow: hidden; }',
  '      .resizer { display: none; }',
  '      #sidebar { width: 100%; height: 100%; max-width: none; background-color: #181818 !important; backdrop-filter: none !important; border-right: none; }',
  '      #main { display: none; width: 100%; height: 100%; }',
  '      body.mobile-mode-editor #sidebar { display: none; }',
  '      body.mobile-mode-editor #main { display: flex; z-index: 20; background: #121212; }',
  '      #mobile-menu-btn { display: none; } #sidebar-close-btn { display: none; } #mobile-back-btn { display: block; background: transparent; border: 1px solid var(--border-glass); color: #fff; padding: 6px 10px; border-radius: 6px; cursor: pointer; margin-right: 8px; font-size: 16px; }',
  '      .toolbar { padding: 10px; gap: 8px; } .toolbar-input { width: 100%; flex: 1; } .primary { flex: none; padding: 6px 12px; font-size: 12px; } #status { display: none; }',
  '      .actions { opacity: 1; gap: 0px; margin-left: 5px; } .file-item { padding: 10px 6px; } .icon-btn { padding: 6px 4px; font-size: 14px; }',
  '      #upload-progress-container { width: 90%; left: 5%; right: 5%; top: 10px; }',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  ',
  '  <div id="upload-progress-container"></div>',
  '',
  '  <div id="app-container">',
  '    <div id="sidebar">',
  '      <div class="sidebar-header">',
  '        <div class="logo-area"><span>☁️ QRJ云盘 Cloud</span></div>',
  '        <div class="header-actions">',
  '           <button class="glass-btn" onclick="triggerFileUpload()" title="上传文件">📤 上传文件</button>',
  '           <button class="glass-btn" onclick="handleSidebarNewFile()">📄 新建</button>',
  '           <button class="glass-btn" onclick="createEntry(\'folder\')">📁 文件夹</button>',
  '           <button class="glass-btn btn-icon" onclick="reloadList()" title="刷新">↻</button>',
  '           <input type="file" id="hidden-file-input" multiple style="display:none">',
  '        </div>',
  '        <div class="path-bar" id="current-path-display">Connecting...</div>',
  '      </div>',
  '      <div id="file-list"></div>',
  '      <div id="sidebar-resizer" class="resizer"></div>',
  '    </div>',
  '    <div id="main">',
  '      <div class="toolbar">',
  '        <button id="mobile-back-btn" onclick="showMobileSidebar()">⬅</button>',
  '        <input type="text" id="filename-input" class="toolbar-input" placeholder="输入文件名...">',
  '        <button class="primary" onclick="prepareNewFile()">新建文件</button>',
  '        <button class="primary" onclick="saveEditorContent()">保存文件</button>',
  '        <div style="margin-left: auto; display: flex; align-items: center; gap: 6px;">',
  '             <span id="status">Ready</span>',
  '             <button onclick="toggleBg()" style="background:transparent; border:none; color:rgba(255,255,255,0.3); cursor:pointer; font-size:18px; padding:0; display:flex; align-items:center;" title="切换背景">🎨</button>',
  '        </div>',
  '      </div>',
  '      <textarea id="editor" placeholder="// Select a file..."></textarea>',
  '    </div>',
  '  </div>',
  '',
  '  <div id="context-menu" class="context-menu">',
  '      <div class="menu-item" onclick="execMenu(\'open\')">📄 打开</div>',
  '      <div class="menu-item" onclick="execMenu(\'share\')">🌐 在线浏览/分享</div>',
  '      <div class="menu-separator"></div>',
  '      <div class="menu-item" onclick="execMenu(\'rename\')">✎ 重命名</div>',
  '      <div class="menu-item" onclick="execMenu(\'cut\')">✂️ 剪切</div>',
  '      <div class="menu-item" onclick="execMenu(\'copy\')">📑 复制</div>',
  '      <div class="menu-item" id="menu-paste" onclick="execMenu(\'paste\')">📋 粘贴</div>',
  '      <div class="menu-separator"></div>',
  '      <div class="menu-item" onclick="execMenu(\'move\')">➜ 移动...</div>',
  '      <div class="menu-item" onclick="execMenu(\'copy_link\')">🔗 复制链接</div>',
  '      <div class="menu-item" onclick="execMenu(\'download\')">⬇ 下载</div>',
  '      <div class="menu-separator"></div>',
  '      <div class="menu-item" onclick="execMenu(\'info\')">ℹ 属性</div>',
  '      <div class="menu-item" onclick="execMenu(\'delete\')" style="color:var(--danger-color)">× 删除</div>',
  '  </div>',
  '',
  '  <div id="login-modal" class="modal-overlay" style="display: flex;">',
  '    <div class="modal-box login-box">',
  '       <div class="modal-body" style="padding: 30px 25px;">',
  '           <span class="login-title">🔐 QRJ Cloud Login</span>',
  '           <div class="login-input-group"><input type="text" id="login-user" class="login-input" placeholder="Username" autocomplete="username"></div>',
  '           <div class="login-input-group"><input type="password" id="login-pass" class="login-input" placeholder="Password" autocomplete="current-password"></div>',
  '           <button class="primary login-btn" onclick="performLogin()">登录 →</button>',
  '       </div>',
  '    </div>',
  '  </div>',
  '',
  '  <div id="move-modal" class="modal-overlay">',
  '    <div class="modal-box">',
  '       <div class="modal-header"><span id="move-title">移动文件</span><span class="modal-close" onclick="closeModal(\'move-modal\')">✕</span></div>',
  '       <div class="modal-body">',
  '           <p style="color:#aaa; margin-bottom:5px; font-size:12px;">选择目标文件夹:</p>',
  '           <select id="move-folder-select" class="folder-select" onchange="updateMoveInput()"></select>',
  '           <p style="color:#aaa; margin-bottom:5px; font-size:12px;">目标完整路径 (可编辑):</p>',
  '           <input type="text" id="move-input" class="full-width-input" spellcheck="false">',
  '       </div>',
  '       <div class="modal-footer">',
  '           <button class="glass-btn" onclick="closeModal(\'move-modal\')">取消</button>',
  '           <button class="primary" onclick="submitMove()">确认移动</button>',
  '       </div>',
  '    </div>',
  '  </div>',
  '',
  '  <div id="info-modal" class="modal-overlay">',
  '    <div class="modal-box">',
  '       <div class="modal-header"><span id="modal-title">Info</span><span class="modal-close" onclick="closeModal(\'info-modal\')">✕</span></div>',
  '       <div class="modal-body" id="modal-content">Loading...</div>',
  '    </div>',
  '  </div>',
  '',
  '  <div id="confirm-modal" class="modal-overlay">',
  '    <div class="modal-box">',
  '       <div class="modal-header"><span id="confirm-title">确认操作</span><span class="modal-close" onclick="closeModal(\'confirm-modal\')">✕</span></div>',
  '       <div class="modal-body" id="confirm-message"></div>',
  '       <div class="modal-footer">',
  '           <button class="glass-btn" onclick="closeModal(\'confirm-modal\')">取消</button>',
  '           <button id="confirm-btn-ok" class="primary danger-btn">确认删除</button>',
  '       </div>',
  '    </div>',
  '  </div>',
  '',
  '  <script>',
  '    var currentPrefix = "";',
  '    var authToken = null;',
  '    var availableFolders = [];',
  '    var currentEditingKey = null;',
  '    var isUnsaved = false;',
  '    var editor = document.getElementById("editor");',
  '    var filenameInput = document.getElementById("filename-input");',
  '    var statusMsg = document.getElementById("status");',
  '    var pathDisplay = document.getElementById("current-path-display");',
  '    var sidebar = document.getElementById("sidebar");',
  '    var fileInput = document.getElementById("hidden-file-input");',
  '    var loginModal = document.getElementById("login-modal");',
  '    var contextMenu = document.getElementById("context-menu");',
  '    var isRenaming = false;',
  '    var isRenamingProcessing = false;',
  '    var targetMoveKey = null; var targetMoveIsFolder = false; var targetMoveName = "";',
  '    var clipboardAction = null; var clipboardSource = null; var clipboardIsFolder = false;',
  '    var ctxTargetKey = null; var ctxIsFolder = false; var ctxTargetEl = null;',
  '',
  '    /* --- 侧边栏拖拽 --- */',
  '    var resizer = document.getElementById("sidebar-resizer");',
  '    var isResizingSidebar = false;',
  '    resizer.addEventListener("mousedown", function(e) {',
  '        isResizingSidebar = true; resizer.classList.add("resizing");',
  '        document.body.style.cursor = "col-resize"; document.body.style.userSelect = "none";',
  '        e.preventDefault();',
  '    });',
  '    document.addEventListener("mousemove", function(e) {',
  '        if (!isResizingSidebar) return;',
  '        var containerLeft = document.getElementById("app-container").getBoundingClientRect().left;',
  '        var newWidth = e.clientX - containerLeft;',
  '        if (newWidth > 240 && newWidth < 600) sidebar.style.width = newWidth + "px";',
  '    });',
  '    document.addEventListener("mouseup", function() {',
  '        if (isResizingSidebar) {',
  '            isResizingSidebar = false; resizer.classList.remove("resizing");',
  '            document.body.style.cursor = ""; document.body.style.userSelect = "";',
  '        }',
  '    });',
  '',
  '    var currentBgState = 0; ',
  '    const bg1 = "https://bing.img.run/rand_1366x768.php";',
  '    const bg2 = "https://gips0.baidu.com/it/u=2864904819,3156938601&fm=3074&app=3074&f=PNG?w=2560&h=1440";',
  '    function toggleBg() {',
  '        currentBgState = 1 - currentBgState;',
  '        var url = currentBgState === 0 ? bg1 : bg2;',
  '        document.body.style.backgroundImage = "url(\'" + url + "\')";',
  '    }',
  '',
  '    function showMobileEditor() { document.body.classList.add("mobile-mode-editor"); }',
  '    function showMobileSidebar() { document.body.classList.remove("mobile-mode-editor"); }',
  '',
  '    editor.addEventListener("input", function() { isUnsaved = true; statusMsg.innerText = "Editing..."; });',
  '',
  '    async function handleFilenameBlur() {',
  '        if (!currentEditingKey || isRenamingProcessing) return;',
  '        var newName = filenameInput.value.trim();',
  '        var oldName = currentEditingKey.split("/").pop();',
  '        if (!newName || newName === oldName) return;',
  '        isRenamingProcessing = true;',
  '        var newKey = currentPrefix + newName;',
  '        statusMsg.innerText = "Renaming...";',
  '        try {',
  '            var res = await apiFetch("/api/rename", { ',
  '                method: "POST", headers: {"Content-Type": "application/json"}, ',
  '                body: JSON.stringify({ oldKey: currentEditingKey, newKey: newKey, isFolder: false }) ',
  '            });',
  '            if (res.ok) {',
  '                statusMsg.innerText = "Renamed"; currentEditingKey = newKey; reloadList();',
  '            } else {',
  '                if(res.status !== 404) { alert("Rename failed"); filenameInput.value = oldName; }',
  '            }',
  '        } catch(e) { console.error(e); filenameInput.value = oldName; }',
  '        finally { isRenamingProcessing = false; }',
  '    }',
  '    filenameInput.addEventListener("blur", handleFilenameBlur);',
  '    filenameInput.addEventListener("keydown", function(e) { if(e.key === "Enter") { this.blur(); editor.focus(); } });',
  '',
  '    (function initAuth() {',
  '        var savedToken = localStorage.getItem("r2_auth_token");',
  '        var savedTime = localStorage.getItem("r2_auth_time");',
  '        var now = new Date().getTime();',
  '        if (savedToken && savedTime && (now - savedTime < 7 * 24 * 60 * 60 * 1000)) {',
  '            authToken = savedToken; loginModal.style.display = "none"; loadList("");',
  '        } else {',
  '            localStorage.removeItem("r2_auth_token"); localStorage.removeItem("r2_auth_time"); showLoginModal();',
  '        }',
  '    })();',
  '',
  '    async function apiFetch(url, options = {}) {',
  '        if (!authToken) { showLoginModal(); throw new Error("Auth required"); }',
  '        if (!options.headers) options.headers = {};',
  '        options.headers["Authorization"] = "Basic " + authToken;',
  '        const response = await fetch(url, options);',
  '        if (response.status === 401) { authToken = null; showLoginModal(); throw new Error("Auth failed"); }',
  '        return response;',
  '    }',
  '    function showLoginModal() { loginModal.style.display = "flex"; document.getElementById("login-user").focus(); }',
  '    function performLogin() {',
  '        var user = document.getElementById("login-user").value;',
  '        var pass = document.getElementById("login-pass").value;',
  '        if (!user || !pass) return alert("Enter credentials");',
  '        authToken = btoa(user + ":" + pass);',
  '        localStorage.setItem("r2_auth_token", authToken); localStorage.setItem("r2_auth_time", new Date().getTime());',
  '        loginModal.style.display = "none"; loadList("");',
  '    }',
  '    document.getElementById("login-pass").addEventListener("keypress", function(e) { if (e.key === "Enter") performLogin(); });',
  '',
  '    function showContextMenu(e, key, isFolder, element) {',
  '        e.preventDefault();',
  '        ctxTargetKey = key; ctxIsFolder = isFolder; ctxTargetEl = element;',
  '        var pasteBtn = document.getElementById("menu-paste");',
  '        if(clipboardAction) pasteBtn.classList.remove("disabled");',
  '        else pasteBtn.classList.add("disabled");',
  '        contextMenu.style.display = "block";',
  '        var menuWidth = contextMenu.offsetWidth; var menuHeight = contextMenu.offsetHeight;',
  '        var winWidth = window.innerWidth; var winHeight = window.innerHeight;',
  '        var x = e.pageX; var y = e.pageY;',
  '        if (x + menuWidth > winWidth) { x = winWidth - menuWidth - 10; }',
  '        if (y + menuHeight > winHeight) { y = y - menuHeight; }',
  '        if (y < 0) { y = 0; }',
  '        contextMenu.style.left = x + "px"; contextMenu.style.top = y + "px";',
  '    }',
  '    window.addEventListener("click", function() { contextMenu.style.display = "none"; });',
  '',
  '    async function execMenu(action) {',
  '        contextMenu.style.display = "none";',
  '        if(!ctxTargetKey && action !== "paste") return;',
  '        if (action === "open") {',
  '            if (ctxIsFolder) loadList(ctxTargetKey); else openFile(ctxTargetKey, ctxTargetKey.split("/").pop());',
  '        } else if (action === "share") {',
  '            if(ctxIsFolder) alert("Cannot share folder directly"); else viewFile(ctxTargetKey);',
  '        } else if (action === "rename") {',
  '            var btn = ctxTargetEl.querySelector(".rename-btn"); if(btn) triggerRename(btn, ctxTargetKey, ctxIsFolder);',
  '        } else if (action === "cut") {',
  '            clipboardAction = "cut"; clipboardSource = ctxTargetKey; clipboardIsFolder = ctxIsFolder; statusMsg.innerText = "Cut: " + ctxTargetKey.split("/").pop();',
  '        } else if (action === "copy") {',
  '            clipboardAction = "copy"; clipboardSource = ctxTargetKey; clipboardIsFolder = ctxIsFolder; statusMsg.innerText = "Copied: " + ctxTargetKey.split("/").pop();',
  '        } else if (action === "paste") { handlePaste();',
  '        } else if (action === "move") { triggerMove(ctxTargetKey, ctxIsFolder);',
  '        } else if (action === "copy_link") { copyLink(ctxTargetKey);',
  '        } else if (action === "download") { if(ctxIsFolder) alert("N/A"); else downloadFile(ctxTargetKey);',
  '        } else if (action === "info") { if(ctxIsFolder) showFolderInfo(ctxTargetKey); else showFileInfo(ctxTargetKey);',
  '        } else if (action === "delete") { if(ctxIsFolder) deleteFolder(ctxTargetKey); else deleteFile(ctxTargetKey); }',
  '    }',
  '',
  '    async function handlePaste() {',
  '        if (!clipboardAction || !clipboardSource) return;',
  '        var destFolder = currentPrefix;',
  '        if (ctxIsFolder && ctxTargetKey) destFolder = ctxTargetKey;',
  '        var fileName = clipboardIsFolder ? clipboardSource.split("/").slice(-2)[0] + "/" : clipboardSource.split("/").pop();',
  '        var newKey = destFolder + fileName;',
  '        if (newKey === clipboardSource) {',
  '            if (clipboardIsFolder) { var folderName = fileName.slice(0, -1); newKey = destFolder + folderName + " - Copy/"; }',
  '            else { var parts = fileName.split("."); if (parts.length > 1) { var ext = parts.pop(); newKey = destFolder + parts.join(".") + " - Copy." + ext; } else { newKey = destFolder + fileName + " - Copy"; } }',
  '        }',
  '        statusMsg.innerText = "Pasting...";',
  '        try {',
  '            if (clipboardAction === "cut") {',
  '                var res = await apiFetch("/api/rename", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ oldKey: clipboardSource, newKey: newKey, isFolder: clipboardIsFolder }) });',
  '                if(res.ok) { statusMsg.innerText = "Moved"; clipboardAction = null; reloadList(); } else { res.text().then(t => alert("Error: " + t)); }',
  '            } else if (clipboardAction === "copy") {',
  '                var res = await apiFetch("/api/copy", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ srcKey: clipboardSource, destKey: newKey, isFolder: clipboardIsFolder }) });',
  '                if(res.ok) { statusMsg.innerText = "Copied"; reloadList(); } else { res.text().then(t => alert("Error: " + t)); }',
  '            }',
  '        } catch(e) { console.error(e); alert("Paste failed"); }',
  '    }',
  '',
  '    async function autoSavePrevious() {',
  '      if (currentEditingKey && isUnsaved && !editor.disabled) {',
  '          statusMsg.innerText = "Auto-saving...";',
  '          try { await apiFetch("/api/put/" + encodeURIComponent(currentEditingKey), { method: "POST", body: editor.value }); statusMsg.innerText = "Saved (Auto)"; isUnsaved = false; }',
  '          catch(e) { statusMsg.innerText = "Auto-save failed"; console.error(e); }',
  '      }',
  '      isUnsaved = false;',
  '    }',
  '',
  '    async function reloadList() { await autoSavePrevious(); loadList(currentPrefix); }',
  '    function formatSize(bytes) { if (bytes === 0) return "0 B"; var k = 1024; var i = Math.floor(Math.log(bytes) / Math.log(k)); return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + ["B","KB","MB","GB","TB"][i]; }',
  '    function formatTime(seconds) { if (!isFinite(seconds) || seconds < 0) return "--"; if (seconds < 60) return Math.ceil(seconds) + "s"; var m = Math.floor(seconds / 60); var s = Math.ceil(seconds % 60); return m + "m " + s + "s"; }',
  '    function handleDragStart(e, key, isFolder) { e.dataTransfer.setData("text/plain", JSON.stringify({ key: key, isFolder: isFolder })); e.dataTransfer.effectAllowed = "move"; }',
  '    function handleDragOver(e) { e.preventDefault(); e.currentTarget.classList.add("drag-target-hover"); }',
  '    function handleDragLeave(e) { e.currentTarget.classList.remove("drag-target-hover"); }',
  '    async function handleDrop(e, targetFolderPrefix) {',
  '        e.preventDefault(); e.currentTarget.classList.remove("drag-target-hover");',
  '        try {',
  '          var data = JSON.parse(e.dataTransfer.getData("text/plain")); var srcKey = data.key; var srcIsFolder = data.isFolder;',
  '          if(!srcKey || (srcIsFolder && targetFolderPrefix.startsWith(srcKey)) || srcKey === targetFolderPrefix) return;',
  '          var fileName = srcIsFolder ? srcKey.split("/").slice(-2)[0] + "/" : srcKey.split("/").pop(); var newKey = targetFolderPrefix + fileName;',
  '          if(srcKey === newKey) return;',
  '          statusMsg.innerText = "Moving...";',
  '          var res = await apiFetch("/api/rename", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ oldKey: srcKey, newKey: newKey, isFolder: srcIsFolder }) });',
  '          if(res.ok) { statusMsg.innerText = "Moved!"; reloadList(); } else { res.text().then(t => alert("Error: " + t)); }',
  '        } catch(err) { console.error(err); }',
  '    }',
  '',
  '    function viewFile(key) { var url = "/api/share/" + encodeURIComponent(key); window.open(url, "_blank"); }',
  '',
  '    function loadList(prefix) {',
  '      pathDisplay.innerHTML = "Loading...";',
  '      apiFetch("/api/list?prefix=" + encodeURIComponent(prefix)).then(r => r.json()).then(data => {',
  '        currentPrefix = prefix; pathDisplay.innerHTML = "root/ " + (prefix ? prefix : ""); pathDisplay.scrollLeft = pathDisplay.scrollWidth;',
  '        var listDiv = document.getElementById("file-list"); listDiv.innerHTML = ""; availableFolders = data.folders ? data.folders : [];',
  '        if (currentPrefix !== "") {',
  '          var p = currentPrefix.split("/"); p.pop(); p.pop(); var parentPrefix = p.length > 0 ? p.join("/") + "/" : "";',
  '          var div = document.createElement("div"); div.className = "file-item"; div.innerHTML = "<span class=\'file-name\' style=\'color:#aaa\'>🔙 .. (返回上级)</span>";',
  '          div.onclick = goUp; div.ondragover = handleDragOver; div.ondragleave = handleDragLeave; div.ondrop = function(e) { handleDrop(e, parentPrefix); }; div.oncontextmenu = function(e) { showContextMenu(e, parentPrefix, true, this); }; listDiv.appendChild(div);',
  '        }',
  '        if (data.folders) {',
  '          data.folders.sort();',
  '          data.folders.forEach(folderPrefix => {',
  '            var displayName = folderPrefix.slice(currentPrefix.length); var showName = displayName.endsWith("/") ? displayName.slice(0, -1) : displayName;',
  '            var div = document.createElement("div"); div.className = "file-item"; div.draggable = true;',
  '            div.ondragstart = function(e) { handleDragStart(e, folderPrefix, true); }; div.ondragover = handleDragOver; div.ondragleave = handleDragLeave; div.ondrop = function(e) { handleDrop(e, folderPrefix); }; div.oncontextmenu = function(e) { showContextMenu(e, folderPrefix, true, this); };',
  '            var html = "<div class=\'file-name-container\'><span class=\'folder-icon\'>📁</span> <span class=\'file-name\'>" + showName + "</span></div><div class=\'actions\'><button class=\'icon-btn rename-btn\' onclick=\'triggerRename(this, \\"" + folderPrefix + "\\", true)\'>✎</button><button class=\'icon-btn move-btn\' onclick=\'triggerMove(\\"" + folderPrefix + "\\", true)\'>➜</button><button class=\'icon-btn del-btn\' onclick=\'deleteFolder(\\"" + folderPrefix + "\\")\'>×</button></div>";',
  '            div.innerHTML = html;',
  '            div.onclick = async function(e) { if(e.target.tagName === "BUTTON" || e.target.tagName === "INPUT" || isRenaming) return; await autoSavePrevious(); loadList(folderPrefix); };',
  '            listDiv.appendChild(div);',
  '          });',
  '        }',
  '        if (data.files) {',
  '          data.files.sort(function(a, b) { return new Date(b.uploaded) - new Date(a.uploaded); });',
  '          data.files.forEach(f => {',
  '            var displayName = f.key.slice(currentPrefix.length); if(!displayName) return;',
  '            var div = document.createElement("div"); div.className = "file-item"; div.draggable = true;',
  '            div.ondragstart = function(e) { handleDragStart(e, f.key, false); }; div.oncontextmenu = function(e) { showContextMenu(e, f.key, false, this); };',
  '            var keySafe = encodeURIComponent(f.key);',
  '            var html = "<div class=\'file-name-container\'><span class=\'file-icon\'>📄</span> <span class=\'file-name\' title=\'" + f.key + "\'>" + displayName + "</span></div><div class=\'actions\'><button class=\'icon-btn\' onclick=\'viewFile(\\"" + f.key + "\\")\'>🌐</button><button class=\'icon-btn info-btn\' onclick=\'showFileInfo(\\"" + f.key + "\\")\'>ℹ</button><button class=\'icon-btn rename-btn\' onclick=\'triggerRename(this, \\"" + f.key + "\\", false)\'>✎</button><button class=\'icon-btn move-btn\' onclick=\'triggerMove(\\"" + f.key + "\\", false)\'>➜</button><button class=\'icon-btn copy-btn\' onclick=\'copyLink(\\"" + keySafe + "\\")\'>🔗</button><button class=\'icon-btn\' onclick=\'downloadFile(\\"" + keySafe + "\\")\'>⬇</button><button class=\'icon-btn del-btn\' onclick=\'deleteFile(\\"" + f.key + "\\")\'>×</button></div>";',
  '            div.innerHTML = html;',
  '            div.onclick = async function(e) { if(e.target.tagName === "BUTTON" || e.target.tagName === "INPUT" || isRenaming) return; await openFile(f.key, displayName); };',
  '            listDiv.appendChild(div);',
  '          });',
  '        }',
  '      }).catch(e => { console.log(e); });',
  '    }',
  '',
  '    function closeModal(modalId) { document.getElementById(modalId).style.display = "none"; }',
  '    document.querySelectorAll(".modal-overlay").forEach(overlay => { if(overlay.id === "login-modal") return; overlay.addEventListener("click", function(e) { if (e.target === overlay) overlay.style.display = "none"; }); });',
  '',
  '    function triggerRename(btn, oldKey, isFolder) {',
  '        event.stopPropagation(); isRenaming = true;',
  '        var row = btn.closest(".file-item"); row.draggable = false;',
  '        var container = row.querySelector(".file-name-container"); var nameSpan = container.querySelector(".file-name");',
  '        var currentName = nameSpan.innerText; var originalHtml = container.innerHTML;',
  '        container.innerHTML = "<input type=\'text\' class=\'rename-input\' value=\'" + currentName + "\'>";',
  '        var input = container.querySelector("input"); input.focus(); input.oncontextmenu = function(e) { e.stopPropagation(); };',
  '        function submit() {',
  '            var newName = input.value.trim();',
  '            if (!newName || newName === currentName) { container.innerHTML = originalHtml; isRenaming = false; row.draggable = true; return; }',
  '            var newFullKey = isFolder ? oldKey.substring(0, oldKey.length - currentName.length - 1) + newName + "/" : oldKey.substring(0, oldKey.length - currentName.length) + newName;',
  '            statusMsg.innerText = "Renaming...";',
  '            apiFetch("/api/rename", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ oldKey: oldKey, newKey: newFullKey, isFolder: isFolder }) }).then(res => {',
  '                isRenaming = false; row.draggable = true;',
  '                if(res.ok) { statusMsg.innerText = "Renamed"; reloadList(); } else { res.text().then(t => alert("Error: " + t)); container.innerHTML = originalHtml; }',
  '            });',
  '        }',
  '        input.onclick = function(e) { e.stopPropagation(); }; input.onkeydown = function(e) { if(e.key === "Enter") input.blur(); if(e.key === "Escape") { container.innerHTML = originalHtml; isRenaming = false; row.draggable = true; } }; input.onblur = submit;',
  '    }',
  '',
  '    function triggerMove(key, isFolder) {',
  '        event.stopPropagation(); targetMoveKey = key; targetMoveIsFolder = isFolder;',
  '        var parts = key.split("/"); targetMoveName = isFolder ? parts[parts.length - 2] + "/" : parts[parts.length - 1];',
  '        var modal = document.getElementById("move-modal"); var select = document.getElementById("move-folder-select"); var input = document.getElementById("move-input");',
  '        select.innerHTML = ""; var optCurr = document.createElement("option"); optCurr.value = currentPrefix; optCurr.text = "当前目录 (" + (currentPrefix || "Root") + ")"; select.appendChild(optCurr);',
  '        if (currentPrefix !== "") { var optRoot = document.createElement("option"); optRoot.value = ""; optRoot.text = "Root /"; select.appendChild(optRoot); var partsPrefix = currentPrefix.split("/"); partsPrefix.pop(); partsPrefix.pop(); var parentPrefix = partsPrefix.length > 0 ? partsPrefix.join("/") + "/" : ""; var optParent = document.createElement("option"); optParent.value = parentPrefix; optParent.text = "上级目录 (../)"; select.appendChild(optParent); }',
  '        availableFolders.forEach(fp => { if (fp === key) return; var opt = document.createElement("option"); opt.value = fp; opt.text = "📂 " + fp.slice(currentPrefix.length); select.appendChild(opt); });',
  '        input.value = key; modal.style.display = "flex"; input.focus();',
  '    }',
  '    function updateMoveInput() { var select = document.getElementById("move-folder-select"); var input = document.getElementById("move-input"); input.value = select.value + targetMoveName; }',
  '    function submitMove() {',
  '        var newKey = document.getElementById("move-input").value.trim(); if(!newKey || newKey === targetMoveKey) { closeModal("move-modal"); return; }',
  '        if(targetMoveIsFolder && !newKey.endsWith("/")) newKey += "/";',
  '        statusMsg.innerText = "Moving...";',
  '        apiFetch("/api/rename", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ oldKey: targetMoveKey, newKey: newKey, isFolder: targetMoveIsFolder }) }).then(res => { closeModal("move-modal"); if(res.ok) { statusMsg.innerText = "Moved!"; reloadList(); } else { res.text().then(t => alert("Error: " + t)); } });',
  '    }',
  '    function showConfirmDialog(title, messageHtml, actionCallback) { document.getElementById("confirm-title").innerText = title; document.getElementById("confirm-message").innerHTML = messageHtml; var btn = document.getElementById("confirm-btn-ok"); btn.onclick = function() { actionCallback(); closeModal("confirm-modal"); }; document.getElementById("confirm-modal").style.display = "flex"; }',
  '    function renderRow(label, value) { return "<div class=\'info-row\'><span class=\'info-label\'>" + label + "</span><span class=\'info-value\'>" + value + "</span></div>"; }',
  '    function showFileInfo(key) { event.stopPropagation(); document.getElementById("info-modal").style.display = "flex"; document.getElementById("modal-content").innerHTML = "Loading..."; apiFetch("/api/info?key=" + encodeURIComponent(key)).then(r => r.json()).then(info => { var html = renderRow("Name", info.name) + renderRow("Path", info.key) + renderRow("Size", formatSize(info.size)) + renderRow("Type", info.contentType) + renderRow("Date", new Date(info.uploaded).toLocaleString()); document.getElementById("modal-content").innerHTML = html; }); }',
  '    function showFolderInfo(prefix) { event.stopPropagation(); document.getElementById("info-modal").style.display = "flex"; document.getElementById("modal-content").innerHTML = renderRow("Name", prefix) + renderRow("Type", "Directory"); }',
  '    function createEntry(type) { var listDiv = document.getElementById("file-list"); var div = document.createElement("div"); div.className = "file-item new-entry-row"; div.innerHTML = "<div class=\'file-name-container\'>" + (type==="folder"?"📁":"📄") + " <input type=\'text\' class=\'rename-input\'></div>"; listDiv.insertBefore(div, listDiv.firstChild); var input = div.querySelector("input"); input.focus(); input.onblur = function() { var name = input.value.trim(); if(!name) { div.remove(); return; } var newKey = currentPrefix + name + (type==="folder"?"/":""); apiFetch("/api/put/" + encodeURIComponent(newKey), { method: "POST" }).then(() => reloadList()); }; input.onkeydown = function(e) { if(e.key==="Enter") input.blur(); }; }',
  '    async function goUp() { await autoSavePrevious(); var p = currentPrefix.split("/"); p.pop(); p.pop(); loadList(p.length>0 ? p.join("/")+"/" : ""); }',
  '',
  '    /* --- 核心: 打开文件 (新增大小检查防止崩溃) --- */',
  '    async function openFile(key, shortName) {',
  '        await autoSavePrevious();',
  '        currentEditingKey = key;',
  '        isUnsaved = false;',
  '        statusMsg.innerText = "Checking size...";',
  '        filenameInput.value = shortName;',
  '        showMobileEditor();',
  '',
  '        try {',
  '             // 1. 先获取文件信息',
  '             var infoRes = await apiFetch("/api/info?key=" + encodeURIComponent(key));',
  '             if (!infoRes.ok) throw new Error("Info fetch failed");',
  '             var info = await infoRes.json();',
  '',
  '             // 2. 检查大小 (阈值 10MB)',
  '             if (info.size > 10 * 1024 * 1024) {',
  '                 editor.value = "⚠️ 文件过大 (" + formatSize(info.size) + ")，无法在线预览/编辑。\\n请点击右侧下载按钮下载到本地查看。\\n\\n(为防止浏览器内存溢出，已自动屏蔽大文件加载)";',
  '                 editor.disabled = true; // 禁用编辑',
  '                 statusMsg.innerText = "Too large";',
  '                 return;',
  '             }',
  '',
  '             // 3. 安全则加载',
  '             editor.disabled = false;',
  '             statusMsg.innerText = "Loading...";',
  '             apiFetch("/api/get/" + encodeURIComponent(key)).then(r => r.text()).then(t => {',
  '                 editor.value = t;',
  '                 statusMsg.innerText = "Loaded";',
  '             });',
  '        } catch(e) {',
  '             console.error(e);',
  '             editor.value = "Error loading file info.";',
  '             statusMsg.innerText = "Error";',
  '        }',
  '    }',
  '',
  '    async function prepareNewFile() { await autoSavePrevious(); editor.value = ""; editor.disabled = false; filenameInput.value = ""; filenameInput.focus(); statusMsg.innerText = "New File Mode"; document.querySelectorAll(".file-item.active").forEach(el => el.classList.remove("active")); currentEditingKey = null; isUnsaved = false; showMobileEditor(); }',
  '    async function handleSidebarNewFile() { await prepareNewFile(); createEntry("file"); }',
  '    async function saveEditorContent() {',
  '        if(editor.disabled) { alert("此文件无法编辑保存"); return; }',
  '        var newName = filenameInput.value.trim(); if (!newName) return alert("Filename cannot be empty");',
  '        var newKey = currentPrefix + newName;',
  '        if (currentEditingKey && newKey !== currentEditingKey) {',
  '            if (isRenamingProcessing) { statusMsg.innerText = "Waiting for rename..."; while(isRenamingProcessing) await new Promise(r => setTimeout(r, 100)); }',
  '            if (newKey !== currentEditingKey) {',
  '                statusMsg.innerText = "Renaming & Saving...";',
  '                try { var res = await apiFetch("/api/rename", { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({ oldKey: currentEditingKey, newKey: newKey, isFolder: false }) }); if (res.ok) { currentEditingKey = newKey; } else { var t = await res.text(); if (!confirm("Rename failed (" + t + "). Save as new file?")) return; } } catch(e) { alert("Error during rename: " + e); return; }',
  '            }',
  '        }',
  '        apiFetch("/api/put/" + encodeURIComponent(newKey), { method: "POST", body: editor.value }).then(() => { statusMsg.innerText = "Saved"; currentEditingKey = newKey; isUnsaved = false; reloadList(); });',
  '    }',
  '    function deleteFile(key) { event.stopPropagation(); showConfirmDialog("Del File", "Delete " + key + "?", () => apiFetch("/api/delete/" + encodeURIComponent(key), { method: "DELETE" }).then(() => { reloadList(); showMobileSidebar(); })); }',
  '    function deleteFolder(key) { event.stopPropagation(); showConfirmDialog("Del Folder", "Delete " + key + "?", () => apiFetch("/api/delete_folder/" + encodeURIComponent(key), { method: "DELETE" }).then(() => reloadList())); }',
  '    async function downloadFile(key) { event.stopPropagation(); var res = await apiFetch("/api/download/" + key); var blob = await res.blob(); var url = window.URL.createObjectURL(blob); var a = document.createElement("a"); a.href = url; a.download = key.split("/").pop(); a.click(); }',
  '    function copyLink(key) { event.stopPropagation(); navigator.clipboard.writeText(window.location.origin + "/api/download/" + key); statusMsg.innerText = "Copied"; }',
  '    function triggerFileUpload() { fileInput.click(); }',
  '    fileInput.addEventListener("change", function(e) { if(this.files.length) uploadFiles(this.files); this.value=""; });',
  '    function preventDefaults(e) { e.preventDefault(); e.stopPropagation(); }',
  '    ["dragenter", "dragover", "dragleave", "drop"].forEach(eventName => sidebar.addEventListener(eventName, preventDefaults, false));',
  '    sidebar.addEventListener("drop", function(e) { sidebar.classList.remove("drag-active"); if(e.dataTransfer.files.length) uploadFiles(e.dataTransfer.files); }, false);',
  '',
  '    /* --- 核心: 创建进度条 UI (升级版) --- */',
  '    function createProgressUI(filename) {',
  '        var container = document.getElementById("upload-progress-container");',
  '        var div = document.createElement("div"); div.className = "progress-card";',
  '        div.innerHTML = "<div class=\'progress-header\'><span class=\'progress-filename\'>" + filename + "</span><span class=\'progress-percent\'>0%</span></div><div class=\'progress-bar-bg\'><div class=\'progress-bar-fill\'></div></div><div class=\'progress-details\'><span>Speed: -</span><span>ETA: -</span></div>";',
  '        container.appendChild(div);',
  '        return {',
  '            update: function(percent, speedStr, etaStr) {',
  '                div.querySelector(".progress-percent").innerText = percent + "%";',
  '                div.querySelector(".progress-bar-fill").style.width = percent + "%";',
  '                var details = div.querySelectorAll(".progress-details span");',
  '                if(speedStr) details[0].innerText = speedStr;',
  '                if(etaStr) details[1].innerText = "ETA: " + etaStr;',
  '            },',
  '            done: function() {',
  '                this.update(100, "Done", "0s"); setTimeout(() => { div.style.opacity="0"; setTimeout(() => div.remove(), 300); }, 1500);',
  '            },',
  '            error: function() {',
  '                div.querySelector(".progress-percent").innerText = "Error";',
  '                div.querySelector(".progress-bar-fill").style.background = "red";',
  '            }',
  '        };',
  '    }',
  '',
  '    /* --- 核心: 多文件并发上传逻辑 (修正阻塞问题) --- */',
  '    async function uploadFiles(files) {',
  '        /* 将 FileList 转换为数组，以便使用 map 进行并发操作 */',
  '        var filesArray = Array.from(files);',
  '        ',
  '        statusMsg.innerText = "Processing " + filesArray.length + " files...";',
  '',
  '        /* 映射每个文件为上传 Promise */',
  '        var uploadPromises = filesArray.map(async function(file) {',
  '            var key = currentPrefix + file.name;',
  '            var ui = createProgressUI(file.name);',
  '            var startTime = Date.now();',
  '            ',
  '            try {',
  '                /* 小于 50MB 直接上传 */',
  '                if (file.size < 50 * 1024 * 1024) {',
  '                     await new Promise((resolve, reject) => {',
  '                          var xhr = new XMLHttpRequest();',
  '                          xhr.open("POST", "/api/put/" + encodeURIComponent(key), true);',
  '                          xhr.setRequestHeader("Authorization", "Basic " + authToken);',
  '                          xhr.upload.onprogress = function(e) {',
  '                              if (e.lengthComputable) { ',
  '                                  var percent = Math.round((e.loaded / e.total) * 100); ',
  '                                  var elapsed = (Date.now() - startTime) / 1000;',
  '                                  var speed = elapsed > 0 ? e.loaded / elapsed : 0; // Bytes/s',
  '                                  var remainingBytes = e.total - e.loaded;',
  '                                  var eta = speed > 0 ? remainingBytes / speed : 0;',
  '                                  ui.update(percent, formatSize(speed) + "/s", formatTime(eta));',
  '                              }',
  '                          };',
  '                          xhr.onload = function() { if(xhr.status === 200) { ui.done(); resolve(); } else { ui.error(); reject(xhr.responseText); } };',
  '                          xhr.onerror = function() { ui.error(); reject("Network error"); };',
  '                          xhr.send(file);',
  '                     });',
  '                } else {',
  '                     /* 大文件分片上传 */',
  '                     /* 1. 初始化 */',
  '                     var initRes = await apiFetch("/api/mp/create?key=" + encodeURIComponent(key), { method: "POST" });',
  '                     if(!initRes.ok) throw new Error("Init failed");',
  '                     var { uploadId } = await initRes.json();',
  '',
  '                     var chunkSize = 10 * 1024 * 1024; /* 10MB chunk */',
  '                     var chunks = Math.ceil(file.size / chunkSize);',
  '                     var parts = [];',
  '                     var uploadedBytes = 0;',
  '',
  '                     for (var partNum = 0; partNum < chunks; partNum++) {',
  '                          var start = partNum * chunkSize;',
  '                          var end = Math.min(start + chunkSize, file.size);',
  '                          var chunk = file.slice(start, end);',
  '                          ',
  '                          /* 上传分片 */',
  '                          var partRes = await apiFetch("/api/mp/upload?key=" + encodeURIComponent(key) + "&id=" + uploadId + "&part=" + (partNum + 1), {',
  '                              method: "POST", body: chunk',
  '                          });',
  '                          if(!partRes.ok) throw new Error("Part failed");',
  '                          var partData = await partRes.json();',
  '                          parts.push(partData);',
  '                          ',
  '                          uploadedBytes += chunk.size;',
  '                          var percent = Math.round(((partNum + 1) / chunks) * 100);',
  '                          ',
  '                          /* 计算速率 */',
  '                          var elapsed = (Date.now() - startTime) / 1000;',
  '                          var speed = elapsed > 0 ? uploadedBytes / elapsed : 0;',
  '                          var remainingBytes = file.size - uploadedBytes;',
  '                          var eta = speed > 0 ? remainingBytes / speed : 0;',
  '                          ',
  '                          ui.update(percent, formatSize(speed) + "/s", formatTime(eta));',
  '                     }',
  '',
  '                     /* 3. 完成合并 */',
  '                     await apiFetch("/api/mp/complete?key=" + encodeURIComponent(key) + "&id=" + uploadId, {',
  '                          method: "POST", body: JSON.stringify({ parts: parts })',
  '                     });',
  '                     ui.done();',
  '                }',
  '            } catch(e) {',
  '                console.error(e); ui.error(); ',
  '                // 不 alert 阻塞其他文件，只在 UI 显示红条',
  '            }',
  '        });',
  '',
  '        /* 等待所有上传完成（无论成功与否） */',
  '        await Promise.all(uploadPromises);',
  '        statusMsg.innerText = "All Done"; ',
  '        reloadList();',
  '    }',
  '  </script>',
  '</body>',
  '</html>'
  ].join('\n');
   
  export default {
    async fetch(request, env) {
      const url = new URL(request.url);
      const checkAuth = async (req) => {
        const h = req.headers.get('Authorization');
        if (!env.AUTH_USER || !env.AUTH_SECRET) return true;
        try { const [u, p] = atob(h.split(' ')[1]).split(':'); return u === env.AUTH_USER && p === env.AUTH_SECRET; } catch(e) { return false; }
      };
   
      if (!url.pathname.startsWith('/api/')) return new Response(htmlParts, { headers: { 'Content-Type': 'text/html;charset=UTF-8' } });
       
      if (!url.pathname.startsWith('/api/share/') && !url.pathname.startsWith('/api/download/') && !await checkAuth(request)) {
          return new Response('Unauthorized', { status: 401 });
      }
   
      if (url.pathname === '/api/list') {
        const prefix = url.searchParams.get('prefix') || '';
        const list = await env.MY_BUCKET.list({ prefix: prefix, delimiter: '/' });
        return new Response(JSON.stringify({ files: list.objects, folders: list.delimitedPrefixes }), { headers: { 'Content-Type': 'application/json' } });
      }
      if (url.pathname.startsWith('/api/get/')) {
        const obj = await env.MY_BUCKET.get(decodeURIComponent(url.pathname.slice(9)));
        return obj ? new Response(obj.body) : new Response('404', { status: 404 });
      }
      if (url.pathname === '/api/info') {
        const obj = await env.MY_BUCKET.head(url.searchParams.get('key'));
        if(!obj) return new Response('404', { status: 404 });
        return new Response(JSON.stringify({ name: obj.key.split('/').pop(), key: obj.key, size: obj.size, uploaded: obj.uploaded, contentType: obj.httpMetadata?.contentType }), { headers: { 'Content-Type': 'application/json' } });
      }
      if (url.pathname.startsWith('/api/download/')) {
        const obj = await env.MY_BUCKET.get(decodeURIComponent(url.pathname.slice(14)));
        if(!obj) return new Response('404', { status: 404 });
        const h = new Headers(); obj.writeHttpMetadata(h); h.set('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(obj.key.split('/').pop())}`);
        return new Response(obj.body, { headers: h });
      }
      if (url.pathname.startsWith('/api/share/')) {
        const obj = await env.MY_BUCKET.get(decodeURIComponent(url.pathname.slice(11)));
        if(!obj) return new Response('404', { status: 404 });
        const h = new Headers(); 
        obj.writeHttpMetadata(h);
        h.set('Content-Type', 'text/plain; charset=utf-8'); 
        h.set('Content-Disposition', 'inline'); 
        return new Response(obj.body, { headers: h });
      }
      if (url.pathname.startsWith('/api/put/')) {
        if(request.method !== 'POST') return new Response('405', { status: 405 });
        await env.MY_BUCKET.put(decodeURIComponent(url.pathname.slice(9)), request.body, { httpMetadata: { contentType: request.headers.get('Content-Type') || 'application/octet-stream' } });
        return new Response('Saved');
      }
      /* --- Multipart Upload Backend --- */
      if (url.pathname === '/api/mp/create') {
          if(request.method !== 'POST') return new Response('405', { status: 405 });
          const key = url.searchParams.get('key');
          const multipart = await env.MY_BUCKET.createMultipartUpload(key);
          return new Response(JSON.stringify({ uploadId: multipart.uploadId }), { headers: {'Content-Type': 'application/json'} });
      }
      if (url.pathname === '/api/mp/upload') {
          if(request.method !== 'POST') return new Response('405', { status: 405 });
          const key = url.searchParams.get('key');
          const uploadId = url.searchParams.get('id');
          const partNumber = parseInt(url.searchParams.get('part'));
          const multipart = env.MY_BUCKET.resumeMultipartUpload(key, uploadId);
          const part = await multipart.uploadPart(partNumber, request.body);
          return new Response(JSON.stringify(part), { headers: {'Content-Type': 'application/json'} });
      }
      if (url.pathname === '/api/mp/complete') {
          if(request.method !== 'POST') return new Response('405', { status: 405 });
          const key = url.searchParams.get('key');
          const uploadId = url.searchParams.get('id');
          const { parts } = await request.json();
          const multipart = env.MY_BUCKET.resumeMultipartUpload(key, uploadId);
          await multipart.complete(parts);
          return new Response('Completed');
      }
      /* -------------------------------- */
      if (url.pathname.startsWith('/api/delete/')) {
        if(request.method !== 'DELETE') return new Response('405', { status: 405 });
        await env.MY_BUCKET.delete(decodeURIComponent(url.pathname.slice(12)));
        return new Response('Deleted');
      }
      if (url.pathname === '/api/rename') {
         if(request.method !== 'POST') return new Response('405', { status: 405 });
         const { oldKey, newKey, isFolder } = await request.json();
         try {
             if (isFolder) {
                 let hasMore = true, cursor;
                 while (hasMore) {
                     const list = await env.MY_BUCKET.list({ prefix: oldKey, cursor });
                     for (const obj of list.objects) {
                         const dest = newKey + obj.key.slice(oldKey.length);
                         const src = await env.MY_BUCKET.get(obj.key);
                         await env.MY_BUCKET.put(dest, src.body, { httpMetadata: src.httpMetadata, customMetadata: src.customMetadata });
                         await env.MY_BUCKET.delete(obj.key);
                     }
                     hasMore = list.truncated; cursor = list.cursor;
                 }
             } else {
                 const src = await env.MY_BUCKET.get(oldKey);
                 if(!src) return new Response('404', { status: 404 });
                 await env.MY_BUCKET.put(newKey, src.body, { httpMetadata: src.httpMetadata, customMetadata: src.customMetadata });
                 await env.MY_BUCKET.delete(oldKey);
             }
             return new Response('Renamed');
         } catch (e) { return new Response(e.message, { status: 500 }); }
      }
      if (url.pathname === '/api/copy') {
         if(request.method !== 'POST') return new Response('405', { status: 405 });
         const { srcKey, destKey, isFolder } = await request.json();
         try {
             if (isFolder) {
                 let hasMore = true, cursor;
                 while (hasMore) {
                     const list = await env.MY_BUCKET.list({ prefix: srcKey, cursor });
                     for (const obj of list.objects) {
                         const dest = destKey + obj.key.slice(srcKey.length);
                         const src = await env.MY_BUCKET.get(obj.key);
                         await env.MY_BUCKET.put(dest, src.body, { httpMetadata: src.httpMetadata, customMetadata: src.customMetadata });
                     }
                     hasMore = list.truncated; cursor = list.cursor;
                 }
             } else {
                 const src = await env.MY_BUCKET.get(srcKey);
                 if(!src) return new Response('404', { status: 404 });
                 await env.MY_BUCKET.put(destKey, src.body, { httpMetadata: src.httpMetadata, customMetadata: src.customMetadata });
             }
             return new Response('Copied');
         } catch (e) { return new Response(e.message, { status: 500 }); }
      }
      if (url.pathname.startsWith('/api/delete_folder/')) {
        if(request.method !== 'DELETE') return new Response('405', { status: 405 });
        const prefix = decodeURIComponent(url.pathname.slice(19));
        const list = await env.MY_BUCKET.list({ prefix });
        if(list.objects.length) await env.MY_BUCKET.delete(list.objects.map(o => o.key));
        return new Response('Folder Deleted');
      }
      return new Response('404', { status: 404 });
    }
  };
