/**
 * Cloudflare Worker: R2 Cloud Editor (Multi-Upload Fixed)
 * * 🎨 UI: Sanyue ImgHub 风格 + 玻璃拟态
 * * 🛠️ 新增: 大文件分片上传 (突破 100MB 限制)
 * * 🛠️ 新增: 右上角上传进度悬浮窗 + 🚀 速率/ETA显示
 * * 🛡️ 修复: 10MB 以上文件禁止预览，防止浏览器崩溃
 * * ⚡ 优化: 支持多文件并发上传 (修复只能传一个的问题)
 * * 🛠️ 优化: 改名自动同步、侧边栏拖拽、下载无需鉴权
 * * 🛠️ R2 存储桶绑定 变量名称: MY_BUCKET
 * * 🔐 鉴权用户名密码 变量名称: AUTH_USER / AUTH_SECRET
 */

// --- 1. 前端部分 (HTML + CSS + UI Logic) ---
const htmlParts = [
  '<!DOCTYPE html>',
  '<html lang="zh-CN">',
  '<head>',
  '  <meta charset="UTF-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">',
  '  <title>R2 Cloud Drive</title>',
  '  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>☁️</text></svg>">',
  '  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">',
  '  <style>',
  '    :root {',
  '      --bg-glass: rgba(30, 30, 30, 0.75);',
  '      --bg-glass-lighter: rgba(255, 255, 255, 0.05);',
  '      --bg-glass-sidebar: rgba(20, 20, 20, 0.85);',
  '      --border-glass: rgba(255, 255, 255, 0.1);',
  '      --text-primary: #e0e0e0;',
  '      --text-secondary: #a0a0a0;',
  '      --accent-gradient: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
  '      --danger-gradient: linear-gradient(135deg, #ff6b6b 0%, #c0392b 100%);',
  '      --accent-color: #667eea;',
  '      --danger-color: #ff6b6b;',
  '      --folder-color: #fbd38d;',
  '    }',
  '    ',
  '    body {',
  '      margin: 0;',
  '      font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
  '      background: url("https://bing.img.run/rand_1366x768.php") no-repeat center center fixed;',
  '      background-size: cover;',
  '      height: 100vh;',
  '      overflow: hidden;',
  '      display: flex;',
  '      justify-content: center;',
  '      align-items: center;',
  '      color: var(--text-primary);',
  '      transition: background-image 0.5s ease-in-out;',
  '    }',
  '',
  '    #app-container {',
  '      width: 96%;',
  '      height: 95vh;',
  '      max-width: none;',
  '      background: var(--bg-glass);',
  '      backdrop-filter: blur(20px);',
  '      -webkit-backdrop-filter: blur(20px);',
  '      border-radius: 16px;',
  '      border: 1px solid var(--border-glass);',
  '      box-shadow: 0 16px 40px rgba(0, 0, 0, 0.4);',
  '      display: flex;',
  '      overflow: hidden;',
  '      transition: transform 0.3s ease;',
  '      position: relative;',
  '    }',
  '',
  '    /* --- 侧边栏 --- */',
  '    #sidebar {',
  '      width: 360px;',
  '      min-width: 240px;',
  '      max-width: 600px;',
  '      background: var(--bg-glass-sidebar);',
  '      border-right: 1px solid var(--border-glass);',
  '      display: flex;',
  '      flex-direction: column;',
  '      flex-shrink: 0;',
  '      position: relative;',
  '      transition: background 0.3s;',
  '      z-index: 100;',
  '    }',
  '    ',
  '    .resizer {',
  '      width: 5px;',
  '      cursor: col-resize;',
  '      position: absolute;',
  '      top: 0; bottom: 0; right: 0;',
  '      z-index: 101;',
  '      transition: background 0.2s;',
  '    }',
  '    .resizer:hover, .resizer.resizing { background: var(--accent-color); }',
  '    ',
  '    #sidebar.drag-active {',
  '        background: rgba(102, 126, 234, 0.15);',
  '        box-shadow: inset 0 0 20px rgba(102, 126, 234, 0.3);',
  '        border-right: 2px dashed var(--accent-color);',
  '    }',
  '    #sidebar.drag-active::after {',
  '        content: "⬇️ 松手以上传文件到当前目录";',
  '        position: absolute;',
  '        top: 50%; left: 50%; transform: translate(-50%, -50%);',
  '        color: #fff; font-weight: bold; font-size: 16px;',
  '        pointer-events: none; text-align: center;',
  '        background: rgba(0,0,0,0.6); padding: 10px 20px; border-radius: 8px; z-index: 50;',
  '    }',
  '',
  '    .sidebar-header { padding: 20px; border-bottom: 1px solid var(--border-glass); }',
  '    #mobile-menu-btn, #mobile-back-btn { display: none; }',
  '',
  '    .logo-area { font-size: 18px; font-weight: 600; margin-bottom: 15px; display: flex; align-items: center; gap: 10px; color: #fff; letter-spacing: 0.5px; }',
  '',
  '    .header-actions { display: flex; gap: 4px; width: 100%; box-sizing: border-box; flex-wrap: wrap; }',
  '    .glass-btn {',
  '      background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.1); color: var(--text-primary);',
  '      padding: 6px 2px; border-radius: 6px; font-size: 12px; cursor: pointer; transition: all 0.3s;',
  '      display: flex; align-items: center; justify-content: center; gap: 2px; flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
  '      min-width: 60px;',
  '    }',
  '    .glass-btn:hover { background: rgba(255,255,255,0.2); transform: translateY(-1px); }',
  '    .btn-icon { flex: 0 0 32px; padding: 0; }',
  '',
  '    .path-bar { margin-top: 15px; font-family: monospace; font-size: 12px; color: var(--text-secondary); background: rgba(0,0,0,0.2); padding: 8px; border-radius: 6px; white-space: nowrap; overflow-x: auto; }',
  '    .path-bar::-webkit-scrollbar { height: 2px; } .path-bar::-webkit-scrollbar-thumb { background: var(--accent-color); }',
  '    #file-list { flex: 1; overflow-y: auto; padding: 10px; }',
  '    #file-list::-webkit-scrollbar { width: 4px; } #file-list::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); border-radius: 2px; }',
  '',
  '    .file-item { padding: 5px 8px; margin-bottom: 2px; border-radius: 6px; cursor: pointer; display: flex; justify-content: space-between; align-items: center; font-size: 13px; transition: all 0.2s; border: 1px solid transparent; }',
  '    .file-item:hover { background: var(--bg-glass-lighter); border-color: rgba(255,255,255,0.05); }',
  '    .file-item.active { background: rgba(102, 126, 234, 0.15); border-color: rgba(102, 126, 234, 0.3); color: #fff; }',
  '    .file-item.drag-target-hover { background: rgba(102, 126, 234, 0.3) !important; border: 1px dashed var(--accent-color) !important; box-shadow: 0 0 10px rgba(102, 126, 234, 0.2); }',
  '',
  '    .file-name-container { display: flex; align-items: center; gap: 8px; flex: 1; overflow: hidden; min-width: 0; }',
  '    .file-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '    .folder-icon { color: var(--folder-color); font-size: 16px; } .file-icon { opacity: 0.7; font-size: 16px; }',
  '    .actions { opacity: 0; transition: opacity 0.2s; display: flex; gap: 0px; } .file-item:hover .actions { opacity: 1; }',
  '    .icon-btn { background: transparent; border: none; color: var(--text-secondary); cursor: pointer; padding: 2px 4px; border-radius: 4px; transition: color 0.2s; font-size: 12px; }',
  '    .icon-btn:hover { color: #fff; background: rgba(255,255,255,0.1); } .del-btn:hover { color: var(--danger-color); }',
  '    .move-btn:hover { color: var(--accent-color); } .rename-btn:hover { color: #4faaff; }',
  '',
  '    /* --- 上下文菜单 --- */',
  '    .context-menu {',
  '       display: none; position: absolute; z-index: 2000;',
  '       background: rgba(40, 40, 40, 0.95);',
  '       border: 1px solid var(--border-glass);',
  '       border-radius: 8px; padding: 6px 0;',
  '       width: 160px; max-height: 80vh; overflow-y: auto;',
  '       box-shadow: 0 10px 30px rgba(0,0,0,0.5);',
  '       backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);',
  '    }',
  '    .context-menu::-webkit-scrollbar { width: 4px; }',
  '    .context-menu::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); border-radius: 2px; }',
  '    .menu-item { padding: 8px 16px; cursor: pointer; color: #eee; font-size: 13px; display: flex; align-items: center; gap: 10px; transition: background 0.2s; }',
  '    .menu-item:hover { background: var(--accent-color); color: #fff; }',
  '    .menu-item.disabled { opacity: 0.5; cursor: not-allowed; }',
  '    .menu-separator { height: 1px; background: rgba(255,255,255,0.1); margin: 4px 0; }',
  '',
  '    /* --- 主编辑区 --- */',
  '    #main { flex: 1; display: flex; flex-direction: column; background: transparent; overflow: hidden; }',
  '    .toolbar { padding: 15px 20px; border-bottom: 1px solid var(--border-glass); display: flex; gap: 15px; align-items: center; }',
  '    .toolbar-input { background: rgba(0,0,0,0.2); border: 1px solid var(--border-glass); color: #fff; padding: 8px 12px; border-radius: 8px; width: 300px; outline: none; font-size: 14px; transition: border-color 0.3s; }',
  '    .toolbar-input:focus { border-color: var(--accent-color); }',
  '    button.primary { background: var(--accent-gradient); color: white; border: none; padding: 8px 20px; border-radius: 50px; font-weight: 500; cursor: pointer; font-size: 13px; box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3); transition: all 0.3s; }',
  '    button.primary:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4); }',
  '    button.primary.danger-btn { background: var(--danger-gradient); box-shadow: 0 4px 15px rgba(255, 107, 107, 0.3); }',
  '    button.primary.danger-btn:hover { box-shadow: 0 6px 20px rgba(255, 107, 107, 0.4); }',
  '    #editor { flex: 1; background: transparent; color: #d4d4d4; border: none; padding: 25px; font-family: "Consolas", "Monaco", monospace; font-size: 14px; resize: none; outline: none; line-height: 1.6; }',
  '    #editor::placeholder { color: rgba(255,255,255,0.2); }',
  '    #editor:disabled { opacity: 0.6; cursor: not-allowed; color: #ff6b6b; font-weight: bold; }',
  '    #status { font-size: 12px; color: var(--text-secondary); opacity: 0.8; }',
  '    .rename-input { background: rgba(0,0,0,0.3); border: 1px solid var(--accent-color); color: white; border-radius: 4px; padding: 2px 5px; width: 90%; }',
  '',
  '    /* --- Toast Notifications (Glassy) --- */',
  '    #toast-container { position: fixed; top: 30px; left: 50%; transform: translateX(-50%); z-index: 4000; display: flex; flex-direction: column; gap: 10px; pointer-events: none; width: auto; align-items: center; }',
  '    .toast { background: rgba(40, 40, 40, 0.85); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.1); padding: 10px 24px; border-radius: 50px; color: #fff; font-size: 14px; box-shadow: 0 10px 30px rgba(0,0,0,0.3); opacity: 0; transform: translateY(-20px); transition: all 0.3s cubic-bezier(0.18, 0.89, 0.32, 1.28); display: flex; align-items: center; gap: 8px; pointer-events: auto; }',
  '    .toast.show { opacity: 1; transform: translateY(0); }',
  '    .toast.error { border-color: rgba(255, 107, 107, 0.4); color: #ffcece; background: rgba(50, 20, 20, 0.9); }',
  '',
  '    /* --- 上传进度悬浮窗 (右上角) --- */',
  '    #upload-progress-container {',
  '        position: fixed; top: 20px; right: 20px; width: 320px; z-index: 3000;',
  '        display: flex; flex-direction: column; gap: 10px;',
  '    }',
  '    .progress-card {',
  '        background: rgba(20, 20, 20, 0.9); border: 1px solid var(--border-glass);',
  '        backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);',
  '        border-radius: 8px; padding: 12px; color: #fff; box-shadow: 0 4px 15px rgba(0,0,0,0.5);',
  '        animation: slideIn 0.3s ease-out;',
  '    }',
  '    @keyframes slideIn { from { transform: translateX(100%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }',
  '    .progress-header { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 5px; }',
  '    .progress-filename { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 180px; }',
  '    .progress-bar-bg { height: 4px; background: rgba(255,255,255,0.1); border-radius: 2px; overflow: hidden; }',
  '    .progress-bar-fill { height: 100%; background: var(--accent-gradient); width: 0%; transition: width 0.2s; }',
  '    .progress-details { display: flex; justify-content: space-between; font-size: 10px; color: #aaa; margin-top: 4px; }',
  '',
  '    /* --- 模态框通用 --- */',
  '    .modal-overlay { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.6); backdrop-filter: blur(8px); z-index: 1000; justify-content: center; align-items: center; }',
  '    .modal-box { background: rgba(40, 40, 40, 0.95); border: 1px solid var(--border-glass); width: 450px; max-width: 90%; border-radius: 16px; box-shadow: 0 25px 50px rgba(0,0,0,0.5); overflow: hidden; animation: fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1); }',
  '    @keyframes fadeIn { from { opacity: 0; transform: scale(0.92); } to { opacity: 1; transform: scale(1); } }',
  '    .modal-header { padding: 20px; border-bottom: 1px solid var(--border-glass); display: flex; justify-content: space-between; align-items: center; font-weight: 600; color: #fff; font-size: 16px; }',
  '    .modal-body { padding: 25px 20px; font-size: 14px; color: #ccc; line-height: 1.6; }',
  '    .modal-footer { padding: 15px 20px; border-top: 1px solid var(--border-glass); display: flex; justify-content: flex-end; gap: 10px; background: rgba(0,0,0,0.2); }',
  '    .modal-close { cursor: pointer; opacity: 0.6; transition: 0.2s; font-size: 18px; } .modal-close:hover { opacity: 1; }',
  '    .info-row { display: flex; margin-bottom: 10px; border-bottom: 1px dashed rgba(255,255,255,0.1); padding-bottom: 8px; }',
  '    .info-label { width: 100px; color: var(--text-secondary); font-size: 13px; }',
  '    .info-value { color: #fff; font-family: monospace; word-break: break-all; font-size: 13px; }',
  '',
  '    .full-width-input { width: 100%; padding: 12px; box-sizing: border-box; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(0,0,0,0.3); color: #fff; outline: none; transition: border-color 0.3s; font-size: 14px; margin-bottom: 10px; }',
  '    .full-width-input:focus { border-color: var(--accent-color); }',
  '    .folder-select { width: 100%; padding: 10px; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(30,30,30,0.8); color: #eee; outline: none; margin-bottom: 15px; }',
  '',
  '    .login-box { width: 380px; text-align: center; }',
  '    .login-title { font-size: 20px; margin-bottom: 20px; display: block; font-weight: bold; background: var(--accent-gradient); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }',
  '    .login-input-group { margin-bottom: 15px; text-align: left; }',
  '    .login-input { width: 100%; padding: 12px; box-sizing: border-box; border-radius: 8px; border: 1px solid var(--border-glass); background: rgba(0,0,0,0.3); color: #fff; outline: none; transition: border-color 0.3s; font-size: 14px; }',
  '    .login-input:focus { border-color: var(--accent-color); }',
  '    .login-btn { width: 100%; padding: 12px; font-size: 16px; margin-top: 10px; }',
  '',
  '    /* --- 移动端 --- */',
  '    @media (max-width: 768px) {',
  '      #app-container { width: 94%; height: 92vh; border-radius: 16px; border: 1px solid var(--border-glass); flex-direction: column; overflow: hidden; }',
  '      .resizer { display: none; }',
  '      #sidebar { width: 100%; height: 100%; max-width: none; background-color: #181818 !important; backdrop-filter: none !important; border-right: none; }',
  '      #main { display: none; width: 100%; height: 100%; }',
  '      body.mobile-mode-editor #sidebar { display: none; }',
  '      body.mobile-mode-editor #main { display: flex; z-index: 20; background: #121212; }',
  '      #mobile-menu-btn { display: none; } #sidebar-close-btn { display: none; } #mobile-back-btn { display: block; background: transparent; border: 1px solid var(--border-glass); color: #fff; padding: 6px 10px; border-radius: 6px; cursor: pointer; margin-right: 8px; font-size: 16px; }',
  '      .toolbar { padding: 10px; gap: 8px; } .toolbar-input { width: 100%; flex: 1; } .primary { flex: none; padding: 6px 12px; font-size: 12px; } #status { display: none; }',
  '      .actions { opacity: 1; gap: 0px; margin-left: 5px; } .file-item { padding: 10px 6px; } .icon-btn { padding: 6px 4px; font-size: 14px; }',
  '      #upload-progress-container { width: 90%; left: 5%; right: 5%; top: 10px; }',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  ',
  '  <div id="toast-container"></div>',
  '  <div id="upload-progress-container"></div>',
  '',
  '  <div id="app-container">',
  '    <div id="sidebar">',
  '      <div class="sidebar-header">',
  '        <div class="logo-area"><span>☁️ QR精云盘 Cloud</span></div>',
  '        <div class="header-actions">',
  '           <button class="glass-btn" onclick="triggerFileUpload()" title="上传文件">📤 上传文件</button>',
  '           <button class="glass-btn" onclick="handleSidebarNewFile()">📄 新建</button>',
  '           <button class="glass-btn" onclick="createEntry(\'folder\')">📁 文件夹</button>',
  '           <button class="glass-btn btn-icon" onclick="reloadList()" title="刷新">↻</button>',
  '           <input type="file" id="hidden-file-input" multiple style="display:none">',
  '        </div>',
  '        <div class="path-bar" id="current-path-display">Connecting...</div>',
  '      </div>',
  '      <div id="file-list"></div>',
  '
